-- 30 new finished items (limit 10 per player - same convention as the existing drink/cake items)
REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('croissant_kareii', 'Croissant Kareii', 10, 0, 1),
	('non_baget', 'Non Baget', 10, 0, 1),
	('keik_shokolat', 'Keik Shokolat', 10, 0, 1),
	('shirini_khamei', 'Shirini Khamei', 10, 0, 1),
	('cookie_shekari', 'Cookie Shekari', 10, 0, 1),
	('roll_darchin', 'Roll Darchin', 10, 0, 1),
	('mocktail_mojito', 'Virgin Mojito', 10, 0, 1),
	('mocktail_pinacolada', 'Virgin Pina Colada', 10, 0, 1),
	('soda_lime', 'Soda Lime', 10, 0, 1),
	('energy_mix', 'Energy Mix', 10, 0, 1),
	('fruit_punch', 'Fruit Punch', 10, 0, 1),
	('ice_tea_special', 'Ice Tea Special', 10, 0, 1),
	('pizza_margherita', 'Pizza Margherita', 10, 0, 1),
	('pizza_pepperoni', 'Pizza Pepperoni', 10, 0, 1),
	('pizza_mushroom', 'Pizza Mushroom', 10, 0, 1),
	('calzone', 'Calzone', 10, 0, 1),
	('garlic_bread', 'Garlic Bread', 10, 0, 1),
	('pizza_bbq_chicken', 'Pizza BBQ Chicken', 10, 0, 1),
	('icecream_vanilla_cone', 'Icecream Vanilla Cone', 10, 0, 1),
	('icecream_chocolate_cone', 'Icecream Chocolate Cone', 10, 0, 1),
	('milkshake_strawberry', 'Milkshake Strawberry', 10, 0, 1),
	('sundae_caramel', 'Sundae Caramel', 10, 0, 1),
	('icecream_sandwich', 'Icecream Sandwich', 10, 0, 1),
	('froyo_mango', 'Froyo Mango', 10, 0, 1),
	('sushi_california', 'Sushi California', 10, 0, 1),
	('sushi_salmon_nigiri', 'Sushi Salmon Nigiri', 10, 0, 1),
	('sushi_dragon_roll', 'Sushi Dragon Roll', 10, 0, 1),
	('sushi_spicy_tuna', 'Sushi Spicy Tuna', 10, 0, 1),
	('miso_soup', 'Miso Soup', 10, 0, 1),
	('sushi_veggie_roll', 'Sushi Veggie Roll', 10, 0, 1);

-- 10 new raw ingredients (limit 30 - same convention as aard/kare/shekar etc.)
REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('khamir_shirini', 'Khamir Shirini', 30, 0, 1),
	('soda_water', 'Soda Water', 30, 0, 1),
	('mive_mix', 'Mive Mix', 30, 0, 1),
	('khamir_pizza', 'Khamir Pizza', 30, 0, 1),
	('sos_gojeh', 'Sos Gojeh', 30, 0, 1),
	('panir_pizza', 'Panir Pizza', 30, 0, 1),
	('khame_yakhi', 'Khame Yakhi', 30, 0, 1),
	('berenj_sushi', 'Berenj Sushi', 30, 0, 1),
	('maahi_khaam', 'Maahi Khaam', 30, 0, 1),
	('nori', 'Nori', 30, 0, 1);
