-- ============================================================
-- uniquecafejobs — COMPLETE database import (v2)
-- Covers: all 17 businesses (incl. original UwU Café menu items)
-- + the 4 holding jobs (Holding 1 / Blacktide / Crate & Carry /
-- Holding 2). All 21 jobs are non-whitelisted (whitelisted=0) so
-- they show up in the F6 job center / esx_joblisting menu.
-- Safe to re-run: REPLACE/IGNORE throughout, and it will NEVER
-- reset an existing business's bank balance.
-- ============================================================

-- Original UwU Café menu items (in case this is a fresh install without them already)
REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('bastani', 'Bastani', 10, 0, 1),
	('boba_milk_tea_caramel', 'Boba Milk Tea Caramel', 10, 0, 1),
	('boba_milk_tea_matcha', 'Boba Milk Tea Matcha', 10, 0, 1),
	('bobal_tea_tamshak', 'Bobal Tea Tamshak', 10, 0, 1),
	('bobal_tea_matcha', 'Bobal Tea Matcha', 10, 0, 1),
	('cake_bastani_vanili', 'Cake Bastani Vanili', 10, 0, 1),
	('cake_limoii', 'Cake Limoii', 10, 0, 1),
	('cupcake_shokolati', 'Cupcake Shokolati', 10, 0, 1),
	('ice_coffee_matcha', 'Ice Coffee Matcha', 10, 0, 1),
	('milk_shake_shokolati', 'Milk Shake Shokolati', 10, 0, 1),
	('mufchocolate', 'Mufchocolate', 10, 0, 1),
	('muffin_tamshak', 'Muffin Tamshak', 10, 0, 1),
	('nodel', 'Nodel', 10, 0, 1),
	('pankik', 'Pankik', 10, 0, 1),
	('pankik_nutella', 'Pankik Nutella', 10, 0, 1),
	('pankik_oreo', 'Pankik Oreo', 10, 0, 1),
	('tiramisuye_toot_farangi', 'Tiramisuye TotFarangi', 10, 0, 1),
	('vafel_nutella', 'Vafel Nutella', 10, 0, 1),
	('abporteghal', 'Ab Porteghal', 10, 0, 1),
	('bubbletetotfarangi', 'Bubblete Totfarangi', 10, 0, 1),
	('cakebastani', 'Cake Bastani', 10, 0, 1),
	('cakebastanivanili', 'Cake Bastani Vanili', 10, 0, 1),
	('caketotfarangi', 'Cake Totfarangi', 10, 0, 1),
	('chaee', 'Chaee', 10, 0, 1),
	('cupcake', 'Cup Cake', 10, 0, 1),
	('ghahve50', 'Ghahve 50', 10, 0, 1),
	('ghahve80', 'Ghahve 80', 10, 0, 1),
	('ghahve100', 'Ghahve 100', 10, 0, 1),
	('hot_chocolate', 'Hot Chocolate', 10, 0, 1),
	('latte', 'Latte', 10, 0, 1),
	('milkshake', 'Milk Shake', 10, 0, 1),
	('noodles', 'Noodles', 10, 0, 1),
	('nutela', 'Nutela', 10, 0, 1),
	('shokolat', 'Shokolat', 10, 0, 1),
	('suop', 'Suop', 10, 0, 1);

REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('vanil', 'Vanil', 30, 0, 1),
	('tamshak', 'Tamshak', 30, 0, 1),
	('powdr_matcha', 'Powdr Matcha', 30, 0, 1),
	('oreo', 'Oreo', 30, 0, 1),
	('nodel_kham', 'Nodel Kham', 30, 0, 1),
	('khame', 'Khame', 30, 0, 1),
	('kare', 'Kare', 30, 0, 1),
	('aard', 'Aard', 30, 0, 1),
	('bakingpowder', 'Baking Powder', 30, 0, 1),
	('daneghahve', 'Dane Ghahve', 30, 0, 1),
	('egg', 'Tokhm Morgh', 30, 0, 1),
	('fenjon', 'Fenjon', 30, 0, 1),
	('fenjonkasif', 'Fenjon Kasif', 30, 0, 1),
	('kase', 'Kase', 30, 0, 1),
	('kasekasif', 'Kase Kasif', 30, 0, 1),
	('limo', 'Limo', 30, 0, 1),
	('podrcacao', 'Podr Cacao', 30, 0, 1),
	('shekar', 'Shekar', 30, 0, 1),
	('shir', 'Shir', 30, 0, 1),
	('totfarangi', 'Tot Farangi', 30, 0, 1),
	('yakh', 'Yakh', 30, 0, 1);


CREATE TABLE IF NOT EXISTS `meridian_portfolio` (
	`business_job` varchar(50) NOT NULL,
	`kind` varchar(10) NOT NULL,
	`status` varchar(10) NOT NULL,
	`rank` varchar(10) DEFAULT NULL,
	PRIMARY KEY (`business_job`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Custom names set by a holding's own Boss (holdings) or by Meridian (businesses)
CREATE TABLE IF NOT EXISTS `custom_names` (
	`entity_job` varchar(50) NOT NULL,
	`custom_label` varchar(50) NOT NULL,
	PRIMARY KEY (`entity_job`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 36 finished items (30 bakery/bar/pizza/icecream/sushi + 6 car wash)
REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('croissant_kareii', 'Croissant Kareii', 10, 0, 1),
	('non_baget', 'Non Baget', 10, 0, 1),
	('keik_shokolat', 'Keik Shokolat', 10, 0, 1),
	('shirini_khamei', 'Shirini Khamei', 10, 0, 1),
	('cookie_shekari', 'Cookie Shekari', 10, 0, 1),
	('roll_darchin', 'Roll Darchin', 10, 0, 1),
	('mocktail_mojito', 'Virgin Mojito', 10, 0, 1),
	('mocktail_pinacolada', 'Virgin Pina Colada', 10, 0, 1),
	('soda_lime', 'Soda Lime', 10, 0, 1),
	('energy_mix', 'Energy Mix', 10, 0, 1),
	('fruit_punch', 'Fruit Punch', 10, 0, 1),
	('ice_tea_special', 'Ice Tea Special', 10, 0, 1),
	('pizza_margherita', 'Pizza Margherita', 10, 0, 1),
	('pizza_pepperoni', 'Pizza Pepperoni', 10, 0, 1),
	('pizza_mushroom', 'Pizza Mushroom', 10, 0, 1),
	('calzone', 'Calzone', 10, 0, 1),
	('garlic_bread', 'Garlic Bread', 10, 0, 1),
	('pizza_bbq_chicken', 'Pizza BBQ Chicken', 10, 0, 1),
	('icecream_vanilla_cone', 'Icecream Vanilla Cone', 10, 0, 1),
	('icecream_chocolate_cone', 'Icecream Chocolate Cone', 10, 0, 1),
	('milkshake_strawberry', 'Milkshake Strawberry', 10, 0, 1),
	('sundae_caramel', 'Sundae Caramel', 10, 0, 1),
	('icecream_sandwich', 'Icecream Sandwich', 10, 0, 1),
	('froyo_mango', 'Froyo Mango', 10, 0, 1),
	('sushi_california', 'Sushi California', 10, 0, 1),
	('sushi_salmon_nigiri', 'Sushi Salmon Nigiri', 10, 0, 1),
	('sushi_dragon_roll', 'Sushi Dragon Roll', 10, 0, 1),
	('sushi_spicy_tuna', 'Sushi Spicy Tuna', 10, 0, 1),
	('miso_soup', 'Miso Soup', 10, 0, 1),
	('sushi_veggie_roll', 'Sushi Veggie Roll', 10, 0, 1),
	('premium_wax', 'Premium Wax', 10, 0, 1),
	('interior_cleaner', 'Interior Cleaner Kit', 10, 0, 1),
	('rim_polish', 'Rim Polish', 10, 0, 1),
	('air_freshener_pine', 'Air Freshener Pine', 10, 0, 1),
	('ceramic_coat', 'Ceramic Coat', 10, 0, 1),
	('tire_shine', 'Tire Shine', 10, 0, 1);

-- 12 new raw ingredients
REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('khamir_shirini', 'Khamir Shirini', 30, 0, 1),
	('soda_water', 'Soda Water', 30, 0, 1),
	('mive_mix', 'Mive Mix', 30, 0, 1),
	('khamir_pizza', 'Khamir Pizza', 30, 0, 1),
	('sos_gojeh', 'Sos Gojeh', 30, 0, 1),
	('panir_pizza', 'Panir Pizza', 30, 0, 1),
	('khame_yakhi', 'Khame Yakhi', 30, 0, 1),
	('berenj_sushi', 'Berenj Sushi', 30, 0, 1),
	('maahi_khaam', 'Maahi Khaam', 30, 0, 1),
	('nori', 'Nori', 30, 0, 1),
	('soap_foam', 'Soap Foam', 30, 0, 1),
	('microfiber_cloth', 'Microfiber Cloth', 30, 0, 1);

-- All 17 business jobs (whitelisted=0 -> visible in the F6 job center)
REPLACE INTO `jobs` (`name`, `label`, `whitelisted`, `handyservice`, `hasapp`, `onlyboss`) VALUES
	('uwucafe', 'Cafe UwU', 0, '0', 0, 0),
	('obsidian', 'Cafe Obsidian', 0, '0', 0, 0),
	('voltage', 'Cafe Voltage', 0, '0', 0, 0),
	('ember', 'Restaurant Ember', 0, '0', 0, 0),
	('anchor', 'Restaurant Anchor', 0, '0', 0, 0),
	('crimson', 'Restaurant Crimson', 0, '0', 0, 0),
	('flourish', 'Bakery Flourish', 0, '0', 0, 0),
	('goldcrust', 'Bakery GoldCrust', 0, '0', 0, 0),
	('static', 'Bar Static', 0, '0', 0, 0),
	('nightjar', 'Bar Nightjar', 0, '0', 0, 0),
	('firebrick', 'Pizza Firebrick', 0, '0', 0, 0),
	('slice', 'Pizza Slice', 0, '0', 0, 0),
	('frostbite', 'Bastani Frostbite', 0, '0', 0, 0),
	('sundae', 'Bastani Sundae', 0, '0', 0, 0),
	('koi', 'Sushi Koi', 0, '0', 0, 0),
	('wasabi', 'Sushi Wasabi', 0, '0', 0, 0),
	('carwash', 'Carwash Suds', 0, '0', 0, 0);

-- The 4 corp/holding jobs (also whitelisted=0)
REPLACE INTO `jobs` (`name`, `label`, `whitelisted`, `handyservice`, `hasapp`, `onlyboss`) VALUES
	('meridian', 'Holding 1', 0, '0', 0, 0),
	('blacktide', 'Blacktide Logistics', 0, '0', 0, 0),
	('cratecarry', 'Crate & Carry Distribution', 0, '0', 0, 0),
	('turfco', 'Holding 2', 0, '0', 0, 0);

-- Grades for all 17 businesses (Rank1-3 + Boss)
REPLACE INTO `job_grades` (`job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`, `vehicles`, `helis`, `weapons`, `items`) VALUES
	('uwucafe', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('uwucafe', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('uwucafe', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('uwucafe', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('obsidian', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('obsidian', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('obsidian', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('obsidian', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('voltage', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('voltage', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('voltage', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('voltage', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('ember', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('ember', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('ember', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('ember', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('anchor', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('anchor', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('anchor', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('anchor', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('crimson', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('crimson', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('crimson', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('crimson', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('flourish', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('flourish', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('flourish', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('flourish', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('goldcrust', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('goldcrust', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('goldcrust', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('goldcrust', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('static', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('static', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('static', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('static', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('nightjar', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('nightjar', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('nightjar', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('nightjar', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('firebrick', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('firebrick', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('firebrick', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('firebrick', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('slice', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('slice', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('slice', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('slice', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('frostbite', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('frostbite', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('frostbite', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('frostbite', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('sundae', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('sundae', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('sundae', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('sundae', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('koi', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('koi', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('koi', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('koi', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('wasabi', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('wasabi', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('wasabi', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('wasabi', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('carwash', 1, 'rank1', 'Rank1', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('carwash', 2, 'rank2', 'Rank2', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('carwash', 3, 'rank3', 'Rank3', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('carwash', 4, 'boss',  'Rank4', 1, '{}', '{}', '[]', '[]', NULL, NULL);

-- Grades for the 4 corp/holding jobs (grade name 'boss' = the rename-authority tier)
REPLACE INTO `job_grades` (`job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`, `vehicles`, `helis`, `weapons`, `items`) VALUES
	('meridian', 1, 'rank1', 'Analyst', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('meridian', 2, 'rank2', 'Director', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('meridian', 3, 'boss', 'CEO', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('blacktide', 1, 'rank1', 'Runner', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('blacktide', 2, 'rank2', 'Enforcer', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('blacktide', 3, 'boss', 'Boss', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('cratecarry', 1, 'rank1', 'Driver', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('cratecarry', 2, 'rank2', 'Manager', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('cratecarry', 3, 'boss', 'Owner', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('turfco', 1, 'rank1', 'Referee', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('turfco', 2, 'rank2', 'Manager', 1, '{}', '{}', '[]', '[]', NULL, NULL),
	('turfco', 3, 'boss', 'Owner', 1, '{}', '{}', '[]', '[]', NULL, NULL);

-- Society inventories (freezers) for every business + holding
REPLACE INTO `addon_inventory` (`name`, `label`, `shared`) VALUES
	('society_uwucafe', 'uwucafe', 1),
	('society_obsidian', 'obsidian', 1),
	('society_voltage', 'voltage', 1),
	('society_ember', 'ember', 1),
	('society_anchor', 'anchor', 1),
	('society_crimson', 'crimson', 1),
	('society_flourish', 'flourish', 1),
	('society_goldcrust', 'goldcrust', 1),
	('society_static', 'static', 1),
	('society_nightjar', 'nightjar', 1),
	('society_firebrick', 'firebrick', 1),
	('society_slice', 'slice', 1),
	('society_frostbite', 'frostbite', 1),
	('society_sundae', 'sundae', 1),
	('society_koi', 'koi', 1),
	('society_wasabi', 'wasabi', 1),
	('society_carwash', 'carwash', 1),
	('society_meridian', 'meridian', 1),
	('society_blacktide', 'blacktide', 1),
	('society_cratecarry', 'cratecarry', 1),
	('society_turfco', 'turfco', 1);

-- Society bank accounts for every business + holding
REPLACE INTO `addon_account` (`name`, `label`, `shared`) VALUES
	('society_uwucafe', 'uwucafe', 1),
	('society_obsidian', 'obsidian', 1),
	('society_voltage', 'voltage', 1),
	('society_ember', 'ember', 1),
	('society_anchor', 'anchor', 1),
	('society_crimson', 'crimson', 1),
	('society_flourish', 'flourish', 1),
	('society_goldcrust', 'goldcrust', 1),
	('society_static', 'static', 1),
	('society_nightjar', 'nightjar', 1),
	('society_firebrick', 'firebrick', 1),
	('society_slice', 'slice', 1),
	('society_frostbite', 'frostbite', 1),
	('society_sundae', 'sundae', 1),
	('society_koi', 'koi', 1),
	('society_wasabi', 'wasabi', 1),
	('society_carwash', 'carwash', 1),
	('society_meridian', 'meridian', 1),
	('society_blacktide', 'blacktide', 1),
	('society_cratecarry', 'cratecarry', 1),
	('society_turfco', 'turfco', 1);

-- Starting balances - INSERT IGNORE so this never resets money on a re-run
INSERT IGNORE INTO `addon_account_data` (`account_name`, `money`, `owner`) VALUES
	('society_uwucafe', 0, NULL),
	('society_obsidian', 0, NULL),
	('society_voltage', 0, NULL),
	('society_ember', 0, NULL),
	('society_anchor', 0, NULL),
	('society_crimson', 0, NULL),
	('society_flourish', 0, NULL),
	('society_goldcrust', 0, NULL),
	('society_static', 0, NULL),
	('society_nightjar', 0, NULL),
	('society_firebrick', 0, NULL),
	('society_slice', 0, NULL),
	('society_frostbite', 0, NULL),
	('society_sundae', 0, NULL),
	('society_koi', 0, NULL),
	('society_wasabi', 0, NULL),
	('society_carwash', 0, NULL),
	('society_meridian', 0, NULL),
	('society_blacktide', 0, NULL),
	('society_cratecarry', 0, NULL),
	('society_turfco', 0, NULL);
