Citizen.CreateThread(function()
    while true do
	Wait(60000)
	   SetWeaponDamageModifier(GetHashKey("weapon_rpg"), 0)
    	Wait(50)
    	SetWeaponDamageModifier(GetHashKey("weapon_grenade"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_stickybomb"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_railgun"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_hominglauncher"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_compactlauncher"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_rayminigun"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_firework"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_grenadelauncher"),0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_pipebomb"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_proxmine"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_SMOKEGRENADE"), 0)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_BZGAS"), 0.25)
        Wait(50)
		SetWeaponDamageModifier(3204302209, 0)
        Wait(50)
		SetWeaponDamageModifier(375527679, 0)
        Wait(50)
		SetWeaponDamageModifier(324506233, 0)
        Wait(50)
		SetWeaponDamageModifier(GetHashKey("WEAPON_UNARMED"), 0.2)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_dagger"), 0.2)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_BAT"), 0.2)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_bottle"), 0.2)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_crowbar"), 0.2)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_flashlight"), 0.2)
        Wait(50)
		SetWeaponDamageModifier(GetHashKey("WEAPON_NIGHTSTICK"), 0.1)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_minigun"), 0.5)
        Wait(50)
		SetWeaponDamageModifier(GetHashKey("WEAPON_PUMPSHOTGUN"), 0.4)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_PUMPSHOTGUN_MK2"), 0.4)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_BULLPUPRIFLE"), 1.2)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_ASSAULTSHOTGUN"), 0.25)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_BULLPUPSHOTGUN"), 0.7)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("WEAPON_SAWNOFFSHOTGUN"), 0.2)
        Wait(50)
		SetWeaponDamageModifier(GetHashKey("weapon_doubleaction"), 0.55)
        Wait(50)
        SetWeaponDamageModifier(GetHashKey("weapon_rpg"), 0)
    	Wait(50)
    end
end)