<?php
declare(strict_types=1);

$lockFile = __DIR__ . '/install.lock';
$localConfigFile = __DIR__ . '/local-config.php';
$alreadyInstalled = file_exists($lockFile);

$errors = [];
$generatedKey = null;

// ---- Requirement checks ----
$checks = [
    'PHP 8.0+' => version_compare(PHP_VERSION, '8.0.0', '>='),
    'PDO SQLite extension' => extension_loaded('pdo_sqlite'),
    'This folder is writable' => is_writable(__DIR__ ),
    'curl extension (for Discord alerts)' => extension_loaded('curl'),
];
$allChecksPassed = !in_array(false, $checks, true);

if ($alreadyInstalled) {
    // Nothing else to do — render the "already installed" screen below.
} elseif (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && $allChecksPassed) {
    $adminPassword = (string)($_POST['admin_password'] ?? '');
    $discordWebhook = trim((string)($_POST['discord_webhook'] ?? ''));
    $brandName = trim((string)($_POST['brand_name'] ?? '')) ?: 'UNIQUE_AC';
    $brandUrl = trim((string)($_POST['brand_url'] ?? '')) ?: 'https://arshiahub.ir';
    $ownerName = trim((string)($_POST['owner_name'] ?? '')) ?: 'Owner';

    if (strlen($adminPassword) < 8) {
        $errors[] = 'Dashboard password must be at least 8 characters.';
    }
    if ($discordWebhook !== '' && !preg_match('#^https://discord(app)?\.com/api/webhooks/#', $discordWebhook)) {
        $errors[] = 'That doesn\'t look like a Discord webhook URL.';
    }

    if (empty($errors)) {
        $configContents = "<?php\n"
            . "// Generated by install.php on " . date('Y-m-d H:i:s') . " — safe to hand-edit later.\n"
            . "define('HUB_ADMIN_PASSWORD', " . var_export($adminPassword, true) . ");\n"
            . "define('HUB_DISCORD_WEBHOOK', " . var_export($discordWebhook, true) . ");\n"
            . "define('HUB_BRAND_NAME', " . var_export($brandName, true) . ");\n"
            . "define('HUB_BRAND_URL', " . var_export($brandUrl, true) . ");\n";

        if (file_put_contents($localConfigFile, $configContents) === false) {
            $errors[] = 'Could not write local-config.php — check folder permissions.';
        } else {
            require __DIR__ . '/lib/db.php'; // this also creates hub.db + tables on first call
            $db = hub_db();

            $generatedKey = 'UAC-' . strtoupper(bin2hex(random_bytes(10)));
            $stmt = $db->prepare('INSERT INTO license_keys (key_value, owner_name, note, max_servers, expires_at, active, created_at) VALUES (:k, :o, :n, :m, NULL, 1, :now)');
            $stmt->execute([':k' => $generatedKey, ':o' => $ownerName, ':n' => 'Created during install', ':m' => 5, ':now' => time()]);

            file_put_contents($lockFile, "Installed " . date('Y-m-d H:i:s') . "\nDelete this file only if you intend to re-run install.php.\n");
            $alreadyInstalled = true;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>UNIQUE_AC Hub — Setup</title>
<link rel="stylesheet" href="dashboard/style.css">
<style>
  body { display: flex; align-items: center; justify-content: center; padding: 24px; }
  .setup-card { width: 100%; max-width: 480px; padding: 32px; border: 1px solid var(--line); border-radius: 4px; background: var(--panel); }
  .setup-card h1 { margin: 0 0 6px; font-size: 22px; } .setup-card h1 span { color: var(--accent); }
  .setup-card .sub { color: var(--muted); font-size: 13px; margin: 0 0 22px; }
  .check-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid var(--line); font-size: 13px; }
  .check-row b.pass { color: var(--success); } .check-row b.fail { color: var(--danger); }
  label { display: block; margin: 16px 0 6px; font: 700 11px var(--font-mono); text-transform: uppercase; letter-spacing: .06em; color: var(--muted); }
  input { width: 100%; padding: 12px 14px; border: 1px solid var(--line); border-radius: 4px; background: rgba(255,255,255,.04); color: var(--text); font-size: 14px; }
  button { width: 100%; margin-top: 24px; padding: 14px; border: 0; border-radius: 4px; background: var(--accent); color: #0A0D0C; font: 800 13px var(--font-mono); text-transform: uppercase; letter-spacing: .05em; cursor: pointer; }
  .msg { padding: 12px 14px; border-radius: 4px; font-size: 13px; margin-bottom: 16px; }
  .msg.error { background: rgba(228,72,58,.12); border: 1px solid rgba(228,72,58,.35); color: #ff9a8f; }
  .msg.success { background: rgba(89,201,122,.12); border: 1px solid rgba(89,201,122,.35); color: var(--success); }
  .key-box { padding: 16px; border: 1px solid var(--accent); border-radius: 4px; background: rgba(56,214,196,.08); text-align: center; margin: 18px 0; }
  .key-box code { display: block; font: 800 15px var(--font-mono); color: var(--accent); margin-top: 8px; word-break: break-all; }
  .next-steps { font-size: 13px; color: var(--muted); line-height: 1.8; }
  .next-steps a { color: var(--accent); }
</style>
</head>
<body>
  <div class="setup-card">
    <h1>UNIQUE<span>_AC</span> Hub Setup</h1>
    <p class="sub">This runs once and builds everything for you — database, admin login, your first license key.</p>

    <?php if ($alreadyInstalled): ?>
      <div class="msg success">✅ Already installed.</div>
      <?php if ($generatedKey): ?>
        <p>Your dashboard is ready. Here's your first license key — paste it into <code>UNIQUE_AC.CentralHub.LicenseKey</code> on your FiveM server:</p>
        <div class="key-box">FIRST LICENSE KEY<code><?= htmlspecialchars($generatedKey) ?></code></div>
      <?php endif; ?>
      <p class="next-steps">
        Next steps:<br>
        1. <a href="dashboard/login.php">Open the dashboard</a> and sign in with the password you just set.<br>
        2. Set up the offline-check cron job — see <a href="README.md">README.md</a>.<br>
        3. <b>Delete or restrict access to install.php now</b> — it's locked, but there's no reason to leave it reachable.
      </p>
    <?php else: ?>
      <?php foreach ($errors as $e): ?><div class="msg error"><?= htmlspecialchars($e) ?></div><?php endforeach; ?>

      <?php foreach ($checks as $label => $passed): ?>
        <div class="check-row"><span><?= htmlspecialchars($label) ?></span><b class="<?= $passed ? 'pass' : 'fail' ?>"><?= $passed ? '✓ OK' : '✗ Missing' ?></b></div>
      <?php endforeach; ?>

      <?php if ($allChecksPassed): ?>
      <form method="post">
        <label>Your name (shown as license owner)</label>
        <input type="text" name="owner_name" required>
        <label>Dashboard password (min. 8 characters)</label>
        <input type="password" name="admin_password" minlength="8" required>
        <label>Discord webhook URL (optional, for offline/Quarantine alerts)</label>
        <input type="text" name="discord_webhook" placeholder="https://discord.com/api/webhooks/...">
        <label>Brand name</label>
        <input type="text" name="brand_name" value="UNIQUE_AC">
        <label>Brand URL</label>
        <input type="text" name="brand_url" value="https://arshiahub.ir">
        <button type="submit">Build the hub</button>
      </form>
      <?php else: ?>
        <p style="color:var(--danger);font-size:13px;margin-top:16px;">Fix the missing requirements above, then reload this page.</p>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</body>
</html>
