Config = {}


Config.AddCoinTrigger = "Coin-System:AddCoinCL"

Config.JobQuests = {
    ["police"] = {
        {name = "Jail Player",
        description = "Jail 3 Player",
        trigger = "quest-police:jail",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Fine Player",
        description = "Fine 5 Player",
        trigger = "quest-police:fine",
        requiredTrigger = 5,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Impound Car",
        description = "Impound 3 Cars",
        trigger = "quest-police:impound",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty",
        description = "Daryaft Salary Onduty",
        trigger = "quest-police:onduty",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Accept Robbery",
        description = "3 Ta Robbery Accept Konid",
        trigger = "quest-police:acceptrob",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Cuff Player",
        description = "Cuff 10 Player",
        trigger = "quest-police:cuff",
        requiredTrigger = 10,
        XP = 10,
        money = 0,
        coin = 0.04},

    },
    ["sheriff"] = {
        {name = "Jail Player",
        description = "Jail 3 Player",
        trigger = "quest-sheriff:jail",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Fine Player",
        description = "Fine 3 Player",
        trigger = "quest-sheriff:fine",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Impound Car",
        description = "Impound 3 Cars",
        trigger = "quest-sheriff:impound",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty",
        description = "Daryaft Salary Onduty",
        trigger = "quest-sheriff:onduty",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Accept Robbery",
        description = "3 Ta Robbery Accept Konid",
        trigger = "quest-sheriff:acceptrob",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Cuff Player",
        description = "Cuff 10 Player",
        trigger = "quest-sheriff:cuff",
        requiredTrigger = 10,
        XP = 10,
        money = 0,
        coin = 0.04},

    },
    ["metropolitan"] = {
        {name = "Jail Player",
        description = "Jail 3 Player",
        trigger = "quest-metropolitan:jail",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Fine Player",
        description = "Fine 3 Player",
        trigger = "quest-metropolitan:fine",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Impound Car",
        description = "Impound 3 Cars",
        trigger = "quest-metropolitan:impound",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty",
        description = "Daryaft Salary Onduty",
        trigger = "quest-metropolitan:onduty",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Accept Robbery",
        description = "3 Ta Robbery Accept Konid",
        trigger = "quest-metropolitan:acceptrob",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Cuff Player",
        description = "Cuff 10 Player",
        trigger = "quest-metropolitan:cuff",
        requiredTrigger = 10,
        XP = 10,
        money = 0,
        coin = 0.04},

    },

    ["ambulance"] = {
        {name = "Revive Player",
        description = "Revive 5 Players",
        trigger = "quest-ambulance:revive",
        requiredTrigger = 5,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Heal Player",
        description = "Heal 5 Players",
        trigger = "quest-ambulance:heal",
        requiredTrigger = 5,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Ghabz",
        description = "5 Ta Ghabz Sader Konid",
        trigger = "quest-ambulance:fine",
        requiredTrigger = 5,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty",
        description = "Daryaft Salary Onduty",
        trigger = "quest-ambulance:onduty",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "accept kardane mogheiat",
        description = "accept kardane mogheiat",
        trigger = "quest-ambulance:acceptreq",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Estefade az Carry 50 Metri",
        description = "Daryaft Salary Onduty",
        trigger = "quest-ambulance:carry",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},
    },

--  ==================================================================== Set Shode ==============================================================

    ["mechanic"] = {
        {name = "Repair Car",
        description = "Repair 5 Cars",
        trigger = "quest-mechanic:repair",
        requiredTrigger = 5,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty",
        description = "Daryaft Salary Onduty",
        trigger = "quest-mechanic:onduty",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

--  ==================================================================== Set Shode ==============================================================

        {name = "Ghabz",
        description = "3 Ta Ghabz Sader Konid",
        trigger = "quest-mechanic:fine",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Custom Car",
        description = "Mashin Haro Custom Konid",
        trigger = "quest-mechanic:custom",
        requiredTrigger = 1,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Clean",
        description = "Mashin Haro Custom Konid",
        trigger = "quest-mechanic:clean",
        requiredTrigger = 1,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Flatbed",
        description = "Mashin Haro Custom Konid",
        trigger = "quest-mechanic:flatbed",
        requiredTrigger = 1,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Impound",
        description = "Mashin Haro Custom Konid",
        trigger = "quest-mechanic:impound",
        requiredTrigger = 1,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Flip",
        description = "Mashin Haro Custom Konid",
        trigger = "quest-mechanic:flip",
        requiredTrigger = 1,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Accept Request",
        description = "Mashin Haro Custom Konid",
        trigger = "quest-mechanic:acceptreq",
        requiredTrigger = 1,
        XP = 10,
        money = 0,
        coin = 0.04},
    },
    ["taxi"] = {
        {name = "Accept Request",
        description = "Accept 3 Request",
        trigger = "quest:revive13",
        requiredTrigger = 3,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Ghabz",
        description = "3 Ta Ghabz Sader Konid",
        trigger = "quest:revive14",
        requiredTrigger = 5,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Spawne Mashin",
        description = "Daryaft Salary Onduty",
        trigger = "quest:revive15",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty1",
        description = "Daryaft Salary Onduty",
        trigger = "quest:revive16",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty2",
        description = "Daryaft Salary Onduty",
        trigger = "quest:revive17",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},

        {name = "Onduty3",
        description = "Daryaft Salary Onduty",
        trigger = "quest:revive18",
        requiredTrigger = 6,
        XP = 10,
        money = 0,
        coin = 0.04},
    }
}


Config.GangQuest = {

    {name = "Complete Shop Robbery",
    description = "Complete a shop robbery",
    trigger = "esx_shop_robbery:RobberyFinished",
    requiredTrigger = 5,
    XP = 500,
    money = 200,
    coin = 5},

    {name = "Complete Bank Robbery",
    description = "Complete a bank robbery",
    trigger = "esx_Bank_robbery:RobberyFinished",
    requiredTrigger = 3,
    XP = 1200,
    money = 500,
    coin = 0.04},

}

Config.DefaultQuest = {
   -- farme mavad --
    {name = "Farme Ephedra",
    description = "50 Ta Ephedra Bardasht Kon",
    trigger = "quest-drug:ephedra",
    requiredTrigger = 50,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Ephedrine",
    description = "100 Ta Ephedrine Besaz",
    trigger = "quest-drug:ephedrine",
    requiredTrigger = 50,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Shishe",
    description = "20 Ta Shishe Besaz",
    trigger = "quest-drug:meth",
    requiredTrigger = 20,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Foroshe Shishe",
    description = "10 Ta Shishe Befrosh",
    trigger = "quest-drug:sellmeth",
    requiredTrigger = 10,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --

    {name = "Farme Shahdane",
    description = "100 Ta Shahdane Bardasht Kon",
    trigger = "quest-drug:cannabis",
    requiredTrigger = 100,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Marijuana",
    description = "500 Ta Marijuana Besaz",
    trigger = "quest-drug:marijuana",
    requiredTrigger = 100,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Forosh Marijuana",
    description = "250 Ta Marijuana Beforsh",
    trigger = "quest-drug:sellmarjuana",
    requiredTrigger = 250,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --

    {name = "Farme Tokme Cocaine",
    description = "200 Ta Tokhm Cocaine Bardasht Kon",
    trigger = "quest-drug:coca",
    requiredTrigger = 200,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Cocaine",
    description = "40 Ta Cocaine Besaz",
    trigger = "quest-drug:cocaine",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Foroshe Cocaine",
    description = "20 Ta Cocaine Befrosh",
    trigger = "quest-drug:sellcocaine",
    requiredTrigger = 20,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Crack",
    description = "80 Ta Crack Besaz",
    trigger = "quest-drug:crack",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Foroshe Crack",
    description = "40 Ta Crack Befrosh",
    trigger = "quest-drug:sellcrack",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --

    {name = "Farme Khash Khaash",
    description = "100 Ta Khash Khaash Bardasht Kon",
    trigger = "quest-drug:poppy",
    requiredTrigger = 100,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Teryak",
    description = "100 Ta Teryak Besaz",
    trigger = "quest-drug:opium",
    requiredTrigger = 20,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Sakhte Heroine",
    description = "20 Ta Heroine Besaz",
    trigger = "quest-drug:heroine",
    requiredTrigger = 20,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Foroshe Heroine",
    description = "10 Ta Heroine Befrosh",
    trigger = "quest-drug:sellheroine",
    requiredTrigger = 10,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --

    {name = "Bardashte Gharch",
    description = "200 Ta Gharch Bardasht Kon",
    trigger = "quest-drug:mushroom",
    requiredTrigger = 200,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Foroshe Gharchh",
    description = "100 Ta Gharch Befrosh",
    trigger = "quest-drug:sellmushroom",
    requiredTrigger = 100,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- -- 
    -- mineri --

    {name = "Bardashte Sang",
    description = "300 Ta Sang Mine Kon",
    trigger = "quest-jobcenter:stonemine",
    requiredTrigger = 300,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Gharbal Sang",
    description = "Sang Haro Gharbal Kon",
    trigger = "quest-jobcenter:gharbal",
    requiredTrigger = 1,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Zobe Ahan",
    description = "Khorde Ahan Haro Zob Kon",
    trigger = "quest-jobcenter:zobahan",
    requiredTrigger = 1,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Zobe Tala",
    description = "Khorde Tala Haro Zob Kon",
    trigger = "quest-jobcenter:zobtala",
    requiredTrigger = 1,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- {name = "Forosh Ajor",
    -- description = "Ajor Hato Befrosh",
    -- trigger = "quest-jobcenter:sellajor",
    -- requiredTrigger = 1,
    -- XP = 10,
    -- money = 100,
    -- coin = 0},

    -- {name = "Forosh Ahan",
    -- description = "2 Ta Ahan Befrosh",
    -- trigger = "quest-jobcenter:sellahan",
    -- requiredTrigger = 2,
    -- XP = 10,
    -- money = 100,
    -- coin = 0},

    -- {name = "Forosh Tala",
    -- description = "2 Ta Tala Befrosh",
    -- trigger = "quest-jobcenter:selltala",
    -- requiredTrigger = 2,
    -- XP = 10,
    -- money = 100,
    -- coin = 0},

    -- {name = "Forosh Diamond",
    -- description = "5 Ta Diamond Befrosh",
    -- trigger = "quest-jobcenter:selldiamond",
    -- requiredTrigger = 5,
    -- XP = 10,
    -- money = 100,
    -- coin = 0},

    -- -- -- --
    -- palayeshgah --

    {name = "Daryafte Benzin Palayeshgah",
    description = "50 Ta Benzin Begir",
    trigger = "quest-jobcenter:petrol",
    requiredTrigger = 50,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Tabdil Raffin",
    description = "100 Ta Raffin Besaz",
    trigger = "quest-jobcenter:raffin",
    requiredTrigger = 50,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Tabdil Assans",
    description = "200 Ta Assans Besaz",
    trigger = "quest-jobcenter:essence",
    requiredTrigger = 100,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --
    -- khayati --

    {name = "Daryafte Pashm",
    description = "160 Ta Pashm Begir",
    trigger = "quest-jobcenter:wool",
    requiredTrigger = 160,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Tabdil Parche",
    description = "80 Ta Parche Tabdil Kon",
    trigger = "quest-jobcenter:fabric",
    requiredTrigger = 80,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Tabdil Lebas",
    description = "40 Ta Lebas Tabdil Kon",
    trigger = "quest-jobcenter:clothe",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --
    -- choob bori --

    {name = "Daryafte Choob",
    description = "50 Ta Choob Begir",
    trigger = "quest-jobcenter:wood",
    requiredTrigger = 50,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Boreshe Choob",
    description = "100 Ta Choob Boresh Bezan",
    trigger = "quest-jobcenter:cutted_wood",
    requiredTrigger = 50,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Baste Bandi Choob",
    description = "20 Ta Choob Baste Bandi Kon",
    trigger = "quest-jobcenter:packaged_plank",
    requiredTrigger = 20,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- --
    -- Morgh Doni --

    {name = "Daryafte Morghe Zende",
    description = "40 Ta Morgh Begir",
    trigger = "quest-jobcenter:alive_chicken",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Zebhe Morgh",
    description = "40 Ta Morgh Zebh Kon",
    trigger = "quest-jobcenter:slaughtered_chicken",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    {name = "Baste Bandi Morgh",
    description = "200 Ta Morgh Baste Bandi Kon",
    trigger = "quest-jobcenter:packaged_chicken",
    requiredTrigger = 40,
    XP = 10,
    money = 0,
    coin = 0.04},

    -- -- -- -- 
}